import type { Course } from '../types';

// The built-in self-study curriculum. Three programs matched to E’TOP's
// class levels; each lesson = new words + a grammar point + exercises.

export const COURSES: Course[] = [
  {
    id: 'kids',
    emoji: '🐣',
    color: 'bg-rose-400',
    titleEn: 'English Start',
    titleVi: 'Khởi động tiếng Anh',
    descEn: 'First words and sentences for young learners',
    descVi: 'Những từ và câu đầu tiên cho các bạn nhỏ',
    levelKeywords: ['Starters', 'Movers'],
    units: [
      {
        id: 'kids_u1',
        titleEn: 'Me & My World',
        titleVi: 'Em và thế giới quanh em',
        lessons: [
          {
            id: 'kids_u1_l1',
            emoji: '👋',
            titleEn: 'Hello!',
            titleVi: 'Xin chào!',
            vocab: [
              { term: 'hello', meaningVi: 'xin chào', example: 'Hello! My name is Mai.' },
              { term: 'goodbye', meaningVi: 'tạm biệt', example: 'Goodbye! See you tomorrow.' },
              { term: 'good morning', meaningVi: 'chào buổi sáng', example: 'Good morning, teacher!' },
              { term: 'friend', meaningVi: 'bạn bè', example: 'Lan is my best friend.' },
              { term: 'name', meaningVi: 'tên', example: 'My name is Nam.' },
              { term: 'teacher', meaningVi: 'thầy / cô giáo', example: 'My teacher is very kind.' },
            ],
            grammar: {
              titleEn: 'I am… / My name is…',
              titleVi: 'I am… / My name is…',
              bodyEn: "Use 'I am…' to introduce yourself and 'My name is…' to say your name.",
              bodyVi: "Dùng 'I am…' (mình là…) để giới thiệu bản thân và 'My name is…' (tên mình là…) để nói tên của em.",
              examples: [
                { en: 'I am Nam.', vi: 'Mình là Nam.' },
                { en: 'My name is Hoa.', vi: 'Tên mình là Hoa.' },
                { en: 'I am seven years old.', vi: 'Mình bảy tuổi.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Chọn câu chào buổi sáng:', options: ['Good morning!', 'Goodbye!', 'Thank you!', 'Sorry!'], answer: 'Good morning!' },
              { kind: 'mc', question: "'Tạm biệt' trong tiếng Anh là gì?", options: ['Hello', 'Goodbye', 'Please', 'Yes'], answer: 'Goodbye' },
              { kind: 'fill', sentence: 'My ___ is Minh.', choices: ['name', 'hello', 'friend'], answer: 'name' },
              { kind: 'fill', sentence: 'I ___ seven years old.', choices: ['am', 'is', 'are'], answer: 'am' },
              { kind: 'order', words: ['My', 'name', 'is', 'Lan'], answer: 'My name is Lan' },
              { kind: 'listen', text: 'Hello! Nice to meet you.', options: ['Hello! Nice to meet you.', 'Goodbye! See you later.', 'Good night!'], answer: 'Hello! Nice to meet you.' },
            ],
          },
          {
            id: 'kids_u1_l2',
            emoji: '👨‍👩‍👧‍👦',
            titleEn: 'My Family',
            titleVi: 'Gia đình em',
            vocab: [
              { term: 'mother', meaningVi: 'mẹ', example: 'My mother cooks yummy food.' },
              { term: 'father', meaningVi: 'bố', example: 'My father is tall.' },
              { term: 'sister', meaningVi: 'chị / em gái', example: 'My sister likes to sing.' },
              { term: 'brother', meaningVi: 'anh / em trai', example: 'My brother plays football.' },
              { term: 'grandmother', meaningVi: 'bà', example: 'My grandmother tells fun stories.' },
              { term: 'family', meaningVi: 'gia đình', example: 'I love my family.' },
            ],
            grammar: {
              titleEn: 'This is my…',
              titleVi: 'This is my…',
              bodyEn: "Use 'This is my…' to introduce people in your family.",
              bodyVi: "Dùng 'This is my…' (đây là… của mình) để giới thiệu người trong gia đình em.",
              examples: [
                { en: 'This is my mother.', vi: 'Đây là mẹ của mình.' },
                { en: 'This is my brother, Nam.', vi: 'Đây là anh trai mình, Nam.' },
                { en: 'I love my family.', vi: 'Mình yêu gia đình mình.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: "'Mẹ' trong tiếng Anh là gì?", options: ['mother', 'father', 'sister', 'teacher'], answer: 'mother' },
              { kind: 'mc', question: 'Chọn câu đúng để giới thiệu bố:', options: ['This is my father.', 'This is my mother.', 'I am father.'], answer: 'This is my father.' },
              { kind: 'fill', sentence: 'This is my ___. She is very kind.', choices: ['grandmother', 'brother', 'father'], answer: 'grandmother' },
              { kind: 'fill', sentence: 'I ___ my family.', choices: ['love', 'am', 'name'], answer: 'love' },
              { kind: 'order', words: ['This', 'is', 'my', 'sister'], answer: 'This is my sister' },
              { kind: 'listen', text: 'My brother plays football.', options: ['My brother plays football.', 'My sister plays football.', 'My father watches TV.'], answer: 'My brother plays football.' },
            ],
          },
          {
            id: 'kids_u1_l3',
            emoji: '🌈',
            titleEn: 'Colours & Numbers',
            titleVi: 'Màu sắc & Con số',
            vocab: [
              { term: 'red', meaningVi: 'màu đỏ', example: 'The apple is red.' },
              { term: 'blue', meaningVi: 'màu xanh dương', example: 'The sky is blue.' },
              { term: 'yellow', meaningVi: 'màu vàng', example: "The E'TOP logo is yellow!" },
              { term: 'green', meaningVi: 'màu xanh lá', example: 'The frog is green.' },
              { term: 'seven', meaningVi: 'số bảy', example: 'I am seven years old.' },
              { term: 'ten', meaningVi: 'số mười', example: 'I have ten fingers.' },
            ],
            grammar: {
              titleEn: 'It is + colour',
              titleVi: 'It is + màu sắc',
              bodyEn: "Use 'It is' + a colour to say what colour something is.",
              bodyVi: "Dùng 'It is' + màu sắc để nói một đồ vật có màu gì.",
              examples: [
                { en: 'It is red.', vi: 'Nó màu đỏ.' },
                { en: 'The sun is yellow.', vi: 'Mặt trời màu vàng.' },
                { en: 'I have two blue pens.', vi: 'Mình có hai cây bút xanh dương.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Quả chuối (banana) thường có màu gì?', options: ['yellow', 'red', 'blue', 'green'], answer: 'yellow' },
              { kind: 'mc', question: "'Số bảy' trong tiếng Anh là gì?", options: ['seven', 'ten', 'six', 'three'], answer: 'seven' },
              { kind: 'fill', sentence: 'The sky is ___.', choices: ['blue', 'yellow', 'red'], answer: 'blue' },
              { kind: 'fill', sentence: 'I have ___ fingers.', choices: ['ten', 'blue', 'red'], answer: 'ten' },
              { kind: 'order', words: ['The', 'apple', 'is', 'red'], answer: 'The apple is red' },
              { kind: 'listen', text: 'The frog is green.', options: ['The frog is green.', 'The dog is brown.', 'The sky is blue.'], answer: 'The frog is green.' },
            ],
          },
        ],
      },
      {
        id: 'kids_u2',
        titleEn: 'School & Play',
        titleVi: 'Trường học & Vui chơi',
        lessons: [
          {
            id: 'kids_u2_l1',
            emoji: '🎒',
            titleEn: 'My School Bag',
            titleVi: 'Cặp sách của em',
            vocab: [
              { term: 'pen', meaningVi: 'bút mực', example: 'I write with a blue pen.' },
              { term: 'book', meaningVi: 'quyển sách', example: 'This book is very fun.' },
              { term: 'ruler', meaningVi: 'thước kẻ', example: 'The ruler is long.' },
              { term: 'school bag', meaningVi: 'cặp sách', example: 'My school bag is heavy.' },
              { term: 'pencil', meaningVi: 'bút chì', example: 'I draw with a pencil.' },
              { term: 'eraser', meaningVi: 'cục tẩy', example: 'Can I borrow your eraser?' },
            ],
            grammar: {
              titleEn: 'I have a…',
              titleVi: 'I have a…',
              bodyEn: "Use 'I have a…' to talk about your things. For more than one, add 's': two pens.",
              bodyVi: "Dùng 'I have a…' (mình có một…) để nói về đồ vật của em. Khi có nhiều hơn một, thêm 's': two pens (hai cây bút).",
              examples: [
                { en: 'I have a new pen.', vi: 'Mình có một cây bút mới.' },
                { en: 'I have two books.', vi: 'Mình có hai quyển sách.' },
                { en: 'She has a pink school bag.', vi: 'Bạn ấy có chiếc cặp màu hồng.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: "'Thước kẻ' trong tiếng Anh là gì?", options: ['ruler', 'eraser', 'pencil', 'pen'], answer: 'ruler' },
              { kind: 'mc', question: 'Chọn câu đúng:', options: ['I have two pens.', 'I have two pen.', 'I has two pens.'], answer: 'I have two pens.' },
              { kind: 'fill', sentence: 'I draw with a ___.', choices: ['pencil', 'book', 'bag'], answer: 'pencil' },
              { kind: 'fill', sentence: 'Can I borrow your ___?', choices: ['eraser', 'morning', 'family'], answer: 'eraser' },
              { kind: 'order', words: ['I', 'have', 'a', 'new', 'book'], answer: 'I have a new book' },
              { kind: 'listen', text: 'My school bag is heavy.', options: ['My school bag is heavy.', 'My school bag is happy.', 'My school book is heavy.'], answer: 'My school bag is heavy.' },
            ],
          },
          {
            id: 'kids_u2_l2',
            emoji: '🐦',
            titleEn: 'Animals Can Do!',
            titleVi: 'Con vật làm được gì?',
            vocab: [
              { term: 'dog', meaningVi: 'con chó', example: 'My dog runs very fast.' },
              { term: 'cat', meaningVi: 'con mèo', example: 'The cat sleeps all day.' },
              { term: 'bird', meaningVi: 'con chim', example: 'The bird sings in the morning.' },
              { term: 'fish', meaningVi: 'con cá', example: 'Fish can swim.' },
              { term: 'jump', meaningVi: 'nhảy', example: 'Rabbits can jump high.' },
              { term: 'fly', meaningVi: 'bay', example: 'Birds can fly.' },
            ],
            grammar: {
              titleEn: 'can / can’t',
              titleVi: 'can / can’t (có thể / không thể)',
              bodyEn: "Use 'can' to say what animals are able to do: Birds can fly. Negative: can't.",
              bodyVi: "Dùng 'can' (có thể) để nói con vật làm được gì: Birds can fly. Phủ định dùng can't (không thể).",
              examples: [
                { en: 'Birds can fly.', vi: 'Chim có thể bay.' },
                { en: 'Fish can swim.', vi: 'Cá có thể bơi.' },
                { en: "Dogs can't fly.", vi: 'Chó không thể bay.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Con gì có thể bay (fly)?', options: ['bird', 'fish', 'dog', 'cat'], answer: 'bird' },
              { kind: 'mc', question: "'Nhảy' trong tiếng Anh là gì?", options: ['jump', 'run', 'swim', 'sleep'], answer: 'jump' },
              { kind: 'fill', sentence: 'Fish can ___.', choices: ['swim', 'fly', 'sing'], answer: 'swim' },
              { kind: 'fill', sentence: 'The cat ___ all day.', choices: ['sleeps', 'sings', 'flies'], answer: 'sleeps' },
              { kind: 'order', words: ['My', 'dog', 'can', 'run', 'fast'], answer: 'My dog can run fast' },
              { kind: 'listen', text: 'Birds can fly.', options: ['Birds can fly.', 'Birds can swim.', 'Bears can fly.'], answer: 'Birds can fly.' },
            ],
          },
          {
            id: 'kids_u2_l3',
            emoji: '🍎',
            titleEn: 'Yummy Food',
            titleVi: 'Món ăn ngon',
            vocab: [
              { term: 'rice', meaningVi: 'cơm', example: 'We eat rice every day.' },
              { term: 'milk', meaningVi: 'sữa', example: 'I drink milk for breakfast.' },
              { term: 'apple', meaningVi: 'quả táo', example: 'An apple a day is good for you.' },
              { term: 'cake', meaningVi: 'bánh kem', example: 'The birthday cake is sweet.' },
              { term: 'chicken', meaningVi: 'thịt gà', example: 'I like fried chicken.' },
              { term: 'water', meaningVi: 'nước', example: 'Drink water every day.' },
            ],
            grammar: {
              titleEn: "I like / I don't like",
              titleVi: "I like / I don't like",
              bodyEn: "Use 'I like…' and 'I don't like…' to talk about food.",
              bodyVi: "Dùng 'I like…' (mình thích) và 'I don't like…' (mình không thích) để nói về món ăn.",
              examples: [
                { en: 'I like apples.', vi: 'Mình thích táo.' },
                { en: "I don't like milk.", vi: 'Mình không thích sữa.' },
                { en: 'Do you like cake? — Yes, I do!', vi: 'Bạn có thích bánh không? — Có!' },
              ],
            },
            exercises: [
              { kind: 'mc', question: "'Cơm' trong tiếng Anh là gì?", options: ['rice', 'cake', 'milk', 'water'], answer: 'rice' },
              { kind: 'mc', question: 'Chọn câu phủ định đúng:', options: ["I don't like milk.", 'I no like milk.', 'I not like milk.'], answer: "I don't like milk." },
              { kind: 'fill', sentence: 'I drink ___ for breakfast.', choices: ['milk', 'cake', 'chicken'], answer: 'milk' },
              { kind: 'fill', sentence: 'Do you ___ cake?', choices: ['like', 'have', 'can'], answer: 'like' },
              { kind: 'order', words: ['I', 'like', 'fried', 'chicken'], answer: 'I like fried chicken' },
              { kind: 'listen', text: 'An apple a day is good for you.', options: ['An apple a day is good for you.', 'An apple a day is bad for you.', 'A banana a day is good for you.'], answer: 'An apple a day is good for you.' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'teens',
    emoji: '🔥',
    color: 'bg-sky-400',
    titleEn: 'Teens Power English',
    titleVi: 'Tiếng Anh Teens năng động',
    descEn: 'Real English for school, friends, and exams',
    descVi: 'Tiếng Anh thực tế cho trường học, bạn bè và thi cử',
    levelKeywords: ['Teens'],
    units: [
      {
        id: 'teens_u1',
        titleEn: 'My Life',
        titleVi: 'Cuộc sống của tôi',
        lessons: [
          {
            id: 'teens_u1_l1',
            emoji: '⏰',
            titleEn: 'My Day',
            titleVi: 'Một ngày của tôi',
            vocab: [
              { term: 'wake up', meaningVi: 'thức dậy', example: "I wake up at six o'clock." },
              { term: 'breakfast', meaningVi: 'bữa sáng', example: 'I eat breakfast with my family.' },
              { term: 'homework', meaningVi: 'bài tập về nhà', example: 'I do my homework after dinner.' },
              { term: 'usually', meaningVi: 'thường', example: 'I usually ride my bike to school.' },
              { term: 'busy', meaningVi: 'bận rộn', example: 'Monday is my busiest day.' },
              { term: 'routine', meaningVi: 'thói quen hằng ngày', example: 'My morning routine is simple.' },
            ],
            grammar: {
              titleEn: 'Present simple',
              titleVi: 'Thì hiện tại đơn',
              bodyEn: "Use the present simple for daily habits. With he/she/it, add 's' to the verb: I wake up → She wakes up.",
              bodyVi: "Dùng thì hiện tại đơn cho thói quen hằng ngày. Với he/she/it, thêm 's' vào động từ: I wake up → She wakes up.",
              examples: [
                { en: 'I wake up at 6 a.m.', vi: 'Tôi thức dậy lúc 6 giờ sáng.' },
                { en: 'She goes to school by bus.', vi: 'Cô ấy đi học bằng xe buýt.' },
                { en: "We don't study on Sundays.", vi: 'Chúng tôi không học vào Chủ nhật.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'She ___ to school at 7 a.m.', options: ['goes', 'go', 'going', 'gone'], answer: 'goes' },
              { kind: 'mc', question: "Từ nào nghĩa là 'bận rộn'?", options: ['busy', 'lazy', 'easy', 'early'], answer: 'busy' },
              { kind: 'fill', sentence: 'I do my ___ after dinner.', choices: ['homework', 'breakfast', 'routine'], answer: 'homework' },
              { kind: 'fill', sentence: "He ___ up at six o'clock.", choices: ['wakes', 'wake', 'waking'], answer: 'wakes' },
              { kind: 'order', words: ['I', 'usually', 'eat', 'breakfast', 'at', 'home'], answer: 'I usually eat breakfast at home' },
              { kind: 'listen', text: "I wake up at six o'clock.", options: ["I wake up at six o'clock.", "I wake up at seven o'clock.", "I go to bed at six o'clock."], answer: "I wake up at six o'clock." },
            ],
          },
          {
            id: 'teens_u1_l2',
            emoji: '🏫',
            titleEn: 'School Life',
            titleVi: 'Đời sống học đường',
            vocab: [
              { term: 'subject', meaningVi: 'môn học', example: 'English is my favourite subject.' },
              { term: 'exam', meaningVi: 'kỳ thi', example: 'We have an exam next week.' },
              { term: 'classmate', meaningVi: 'bạn cùng lớp', example: 'My classmates are friendly.' },
              { term: 'library', meaningVi: 'thư viện', example: 'I read books in the library.' },
              { term: 'never', meaningVi: 'không bao giờ', example: 'I never skip class.' },
              { term: 'favourite', meaningVi: 'yêu thích', example: 'What is your favourite subject?' },
            ],
            grammar: {
              titleEn: 'Adverbs of frequency',
              titleVi: 'Trạng từ tần suất',
              bodyEn: 'always → usually → sometimes → never. They go before the main verb: I always do my homework.',
              bodyVi: 'always (luôn luôn) → usually (thường) → sometimes (thỉnh thoảng) → never (không bao giờ). Đứng trước động từ chính: I always do my homework.',
              examples: [
                { en: 'I always do my homework.', vi: 'Tôi luôn luôn làm bài tập.' },
                { en: 'She sometimes studies in the library.', vi: 'Cô ấy thỉnh thoảng học ở thư viện.' },
                { en: 'We are never late for class.', vi: 'Chúng tôi không bao giờ đi học muộn.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Chọn thứ tự tần suất giảm dần đúng:', options: ['always → sometimes → never', 'never → always → sometimes', 'sometimes → never → always'], answer: 'always → sometimes → never' },
              { kind: 'mc', question: "'Thư viện' trong tiếng Anh là gì?", options: ['library', 'laboratory', 'lobby', 'gallery'], answer: 'library' },
              { kind: 'fill', sentence: 'English is my favourite ___.', choices: ['subject', 'exam', 'classmate'], answer: 'subject' },
              { kind: 'fill', sentence: 'I ___ skip class. (không bao giờ)', choices: ['never', 'always', 'sometimes'], answer: 'never' },
              { kind: 'order', words: ['She', 'always', 'studies', 'before', 'an', 'exam'], answer: 'She always studies before an exam' },
              { kind: 'listen', text: 'We have an exam next week.', options: ['We have an exam next week.', 'We had an exam last week.', 'We have a party next week.'], answer: 'We have an exam next week.' },
            ],
          },
          {
            id: 'teens_u1_l3',
            emoji: '🎮',
            titleEn: 'Free Time & Hobbies',
            titleVi: 'Thời gian rảnh & Sở thích',
            vocab: [
              { term: 'hobby', meaningVi: 'sở thích', example: 'Drawing is my favourite hobby.' },
              { term: 'chess', meaningVi: 'cờ vua', example: 'I play chess with my dad.' },
              { term: 'draw', meaningVi: 'vẽ', example: 'She draws very well.' },
              { term: 'collect', meaningVi: 'sưu tầm', example: 'He collects football cards.' },
              { term: 'relax', meaningVi: 'thư giãn', example: 'Music helps me relax.' },
              { term: 'outdoor', meaningVi: 'ngoài trời', example: 'I love outdoor activities.' },
            ],
            grammar: {
              titleEn: 'like / love / enjoy + V-ing',
              titleVi: 'like / love / enjoy + V-ing',
              bodyEn: 'After like, love, enjoy, and hate, use the -ing form of the verb: I like drawing.',
              bodyVi: 'Sau like, love, enjoy, hate, động từ phía sau thêm -ing: I like drawing (tôi thích vẽ).',
              examples: [
                { en: 'I like drawing.', vi: 'Tôi thích vẽ.' },
                { en: 'She enjoys playing chess.', vi: 'Cô ấy thích chơi cờ vua.' },
                { en: 'They love swimming in summer.', vi: 'Họ thích bơi vào mùa hè.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'I enjoy ___ football.', options: ['playing', 'play', 'plays', 'played'], answer: 'playing' },
              { kind: 'mc', question: "'Sưu tầm' trong tiếng Anh là gì?", options: ['collect', 'connect', 'correct', 'collapse'], answer: 'collect' },
              { kind: 'fill', sentence: 'Music helps me ___.', choices: ['relax', 'draw', 'collect'], answer: 'relax' },
              { kind: 'fill', sentence: 'She loves ___ pictures. (vẽ)', choices: ['drawing', 'draw', 'drew'], answer: 'drawing' },
              { kind: 'order', words: ['I', 'like', 'playing', 'chess', 'with', 'friends'], answer: 'I like playing chess with friends' },
              { kind: 'listen', text: 'Drawing is my favourite hobby.', options: ['Drawing is my favourite hobby.', 'Dancing is my favourite hobby.', 'Drawing is my favourite subject.'], answer: 'Drawing is my favourite hobby.' },
            ],
          },
        ],
      },
      {
        id: 'teens_u2',
        titleEn: 'My World',
        titleVi: 'Thế giới của tôi',
        lessons: [
          {
            id: 'teens_u2_l1',
            emoji: '⚽',
            titleEn: 'Sports & The Past',
            titleVi: 'Thể thao & Quá khứ',
            vocab: [
              { term: 'match', meaningVi: 'trận đấu', example: 'We won the match yesterday!' },
              { term: 'team', meaningVi: 'đội', example: 'Our team has eleven players.' },
              { term: 'train', meaningVi: 'tập luyện', example: 'I train twice a week.' },
              { term: 'win', meaningVi: 'thắng', example: 'I hope we win on Saturday.' },
              { term: 'score', meaningVi: 'ghi bàn', example: 'He scored two goals.' },
              { term: 'healthy', meaningVi: 'khỏe mạnh', example: 'Swimming keeps me healthy.' },
            ],
            grammar: {
              titleEn: 'Past simple',
              titleVi: 'Thì quá khứ đơn',
              bodyEn: 'Talk about finished actions: add -ed (played, trained) or use irregular forms (go → went, win → won). Be: was/were.',
              bodyVi: 'Kể về việc đã xảy ra: thêm -ed (played, trained) hoặc dùng dạng bất quy tắc (go → went, win → won). Động từ be: was/were.',
              examples: [
                { en: 'We played football yesterday.', vi: 'Hôm qua chúng tôi đá bóng.' },
                { en: 'She went to the gym last night.', vi: 'Tối qua cô ấy đến phòng gym.' },
                { en: 'They won the match!', vi: 'Họ đã thắng trận đấu!' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'We ___ the match yesterday.', options: ['won', 'win', 'wins', 'winning'], answer: 'won' },
              { kind: 'mc', question: "Quá khứ của 'go' là gì?", options: ['went', 'goed', 'gone', 'goes'], answer: 'went' },
              { kind: 'fill', sentence: 'I ___ football with my team last Sunday.', choices: ['played', 'play', 'plays'], answer: 'played' },
              { kind: 'fill', sentence: 'Swimming keeps me ___.', choices: ['healthy', 'busy', 'fast'], answer: 'healthy' },
              { kind: 'order', words: ['She', 'went', 'to', 'the', 'gym', 'yesterday'], answer: 'She went to the gym yesterday' },
              { kind: 'listen', text: 'He scored two goals.', options: ['He scored two goals.', 'He scored ten goals.', 'He saw two goats.'], answer: 'He scored two goals.' },
            ],
          },
          {
            id: 'teens_u2_l2',
            emoji: '📱',
            titleEn: 'Technology & Internet',
            titleVi: 'Công nghệ & Internet',
            vocab: [
              { term: 'website', meaningVi: 'trang web', example: 'This website is useful for learning.' },
              { term: 'download', meaningVi: 'tải xuống', example: 'I downloaded a new app.' },
              { term: 'message', meaningVi: 'tin nhắn', example: 'Send me a message tonight.' },
              { term: 'online', meaningVi: 'trực tuyến', example: 'My grandma is online now!' },
              { term: 'device', meaningVi: 'thiết bị', example: 'Put your devices away in class.' },
              { term: 'search', meaningVi: 'tìm kiếm', example: 'Search for the answer online.' },
            ],
            grammar: {
              titleEn: 'Comparatives',
              titleVi: 'So sánh hơn',
              bodyEn: "Short adjectives + er (faster), long adjectives use 'more' (more interesting), than = compared to.",
              bodyVi: "Tính từ ngắn thêm -er (faster: nhanh hơn), tính từ dài dùng 'more' (more interesting: thú vị hơn), than = hơn (so với).",
              examples: [
                { en: 'My new phone is faster than my old one.', vi: 'Điện thoại mới của tôi nhanh hơn cái cũ.' },
                { en: 'This app is more interesting than that one.', vi: 'Ứng dụng này thú vị hơn cái kia.' },
                { en: 'Online learning is cheaper.', vi: 'Học trực tuyến rẻ hơn.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'My new laptop is ___ than my old one.', options: ['faster', 'fast', 'fastest', 'more fast'], answer: 'faster' },
              { kind: 'mc', question: "'Tải xuống' trong tiếng Anh là gì?", options: ['download', 'upload', 'search', 'delete'], answer: 'download' },
              { kind: 'fill', sentence: 'Send me a ___ tonight.', choices: ['message', 'website', 'device'], answer: 'message' },
              { kind: 'fill', sentence: 'This game is ___ interesting than homework.', choices: ['more', 'much', 'very'], answer: 'more' },
              { kind: 'order', words: ['This', 'website', 'is', 'more', 'useful', 'than', 'that', 'one'], answer: 'This website is more useful than that one' },
              { kind: 'listen', text: 'I downloaded a new app.', options: ['I downloaded a new app.', 'I downloaded a new map.', 'I deleted a new app.'], answer: 'I downloaded a new app.' },
            ],
          },
          {
            id: 'teens_u2_l3',
            emoji: '✈️',
            titleEn: 'Travel Plans',
            titleVi: 'Kế hoạch du lịch',
            vocab: [
              { term: 'trip', meaningVi: 'chuyến đi', example: 'We are planning a trip to Da Lat.' },
              { term: 'beach', meaningVi: 'bãi biển', example: 'Mui Ne beach is beautiful.' },
              { term: 'ticket', meaningVi: 'vé', example: 'I bought two train tickets.' },
              { term: 'luggage', meaningVi: 'hành lý', example: "Don't bring too much luggage." },
              { term: 'abroad', meaningVi: 'nước ngoài', example: 'She wants to study abroad.' },
              { term: 'sightseeing', meaningVi: 'tham quan', example: 'We went sightseeing in the old town.' },
            ],
            grammar: {
              titleEn: 'be going to',
              titleVi: 'be going to (sẽ / dự định)',
              bodyEn: "Use 'be going to + verb' for plans: I'm going to visit Da Lat next month.",
              bodyVi: "Dùng 'be going to + động từ' để nói về kế hoạch: I'm going to visit Da Lat (tôi sẽ đi Đà Lạt).",
              examples: [
                { en: "I'm going to visit Da Lat next month.", vi: 'Tháng sau tôi sẽ đi Đà Lạt.' },
                { en: "We're going to swim at the beach.", vi: 'Chúng tôi sẽ bơi ở bãi biển.' },
                { en: "He isn't going to bring much luggage.", vi: 'Anh ấy sẽ không mang nhiều hành lý.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'I ___ going to visit Hue next week.', options: ['am', 'is', 'are', 'be'], answer: 'am' },
              { kind: 'mc', question: "'Hành lý' trong tiếng Anh là gì?", options: ['luggage', 'language', 'lounge', 'luck'], answer: 'luggage' },
              { kind: 'fill', sentence: 'We are going to swim at the ___.', choices: ['beach', 'ticket', 'trip'], answer: 'beach' },
              { kind: 'fill', sentence: 'She wants to study ___.', choices: ['abroad', 'sightseeing', 'luggage'], answer: 'abroad' },
              { kind: 'order', words: ['We', 'are', 'going', 'to', 'visit', 'Mui', 'Ne'], answer: 'We are going to visit Mui Ne' },
              { kind: 'listen', text: 'I bought two train tickets.', options: ['I bought two train tickets.', 'I bought two plane tickets.', 'I brought two train tickets.'], answer: 'I bought two train tickets.' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'adults',
    emoji: '☕',
    color: 'bg-orange-400',
    titleEn: 'Everyday Conversation',
    titleVi: 'Giao tiếp hằng ngày',
    descEn: 'Practical English for daily life and work',
    descVi: 'Tiếng Anh thực dụng cho cuộc sống và công việc',
    levelKeywords: ['Adults', 'IELTS'],
    units: [
      {
        id: 'adults_u1',
        titleEn: 'Out & About',
        titleVi: 'Ra ngoài giao tiếp',
        lessons: [
          {
            id: 'adults_u1_l1',
            emoji: '🥤',
            titleEn: 'At the Café',
            titleVi: 'Tại quán cà phê',
            vocab: [
              { term: 'order', meaningVi: 'gọi món', example: 'Are you ready to order?' },
              { term: 'menu', meaningVi: 'thực đơn', example: 'Can I see the menu, please?' },
              { term: 'bill', meaningVi: 'hóa đơn', example: 'Could we have the bill, please?' },
              { term: 'iced coffee', meaningVi: 'cà phê đá', example: 'One iced coffee, please.' },
              { term: 'takeaway', meaningVi: 'mang đi', example: 'Two sandwiches to take away, please.' },
              { term: 'delicious', meaningVi: 'ngon', example: 'The cake is delicious!' },
            ],
            grammar: {
              titleEn: "I'd like… / Could I have…?",
              titleVi: "I'd like… / Could I have…?",
              bodyEn: "Order politely with \"I'd like…\" and ask politely with \"Could I have…?\"",
              bodyVi: "Gọi món lịch sự với \"I'd like…\" (tôi muốn…) và hỏi lịch sự với \"Could I have…?\" (cho tôi… được không?)",
              examples: [
                { en: "I'd like an iced coffee, please.", vi: 'Cho tôi một cà phê đá.' },
                { en: 'Could I have the menu?', vi: 'Cho tôi xem thực đơn được không?' },
                { en: "Anything else? — No, that's all, thank you.", vi: 'Còn gì nữa không? — Không, đủ rồi, cảm ơn.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Cách gọi món lịch sự nhất:', options: ["I'd like a coffee, please.", 'Give me coffee.', 'Coffee!', 'I want coffee now.'], answer: "I'd like a coffee, please." },
              { kind: 'mc', question: "'Hóa đơn' trong tiếng Anh là gì?", options: ['bill', 'menu', 'order', 'tip'], answer: 'bill' },
              { kind: 'fill', sentence: 'Could I have the ___, please?', choices: ['menu', 'delicious', 'takeaway'], answer: 'menu' },
              { kind: 'fill', sentence: "I'd ___ an iced tea, please.", choices: ['like', 'want', 'take'], answer: 'like' },
              { kind: 'order', words: ['Could', 'we', 'have', 'the', 'bill', 'please'], answer: 'Could we have the bill please' },
              { kind: 'listen', text: 'One iced coffee, please.', options: ['One iced coffee, please.', 'One iced tea, please.', 'Two iced coffees, please.'], answer: 'One iced coffee, please.' },
            ],
          },
          {
            id: 'adults_u1_l2',
            emoji: '🗺️',
            titleEn: 'Asking for Directions',
            titleVi: 'Hỏi đường',
            vocab: [
              { term: 'turn left', meaningVi: 'rẽ trái', example: 'Turn left at the bank.' },
              { term: 'straight', meaningVi: 'thẳng', example: 'Go straight for two blocks.' },
              { term: 'opposite', meaningVi: 'đối diện', example: 'The café is opposite the school.' },
              { term: 'corner', meaningVi: 'góc đường', example: 'The pharmacy is on the corner.' },
              { term: 'far', meaningVi: 'xa', example: 'Is it far from here?' },
              { term: 'between', meaningVi: 'ở giữa', example: 'The bakery is between the bank and the market.' },
            ],
            grammar: {
              titleEn: 'Giving directions',
              titleVi: 'Chỉ đường',
              bodyEn: 'Use imperatives: Turn left, Go straight. Describe position with opposite, between, on the corner.',
              bodyVi: 'Chỉ đường dùng câu mệnh lệnh: Turn left (rẽ trái), Go straight (đi thẳng). Mô tả vị trí: opposite (đối diện), between (ở giữa), on the corner (ở góc đường).',
              examples: [
                { en: 'Turn right at the traffic lights.', vi: 'Rẽ phải ở đèn giao thông.' },
                { en: "Go straight and it's on your left.", vi: 'Đi thẳng, nó nằm bên trái bạn.' },
                { en: 'Excuse me, where is the bank?', vi: 'Xin lỗi, ngân hàng ở đâu ạ?' },
              ],
            },
            exercises: [
              { kind: 'mc', question: "'Rẽ trái' trong tiếng Anh là gì?", options: ['Turn left', 'Turn right', 'Go straight', 'Stop'], answer: 'Turn left' },
              { kind: 'mc', question: 'The café is ___ the school. (đối diện)', options: ['opposite', 'between', 'far', 'corner'], answer: 'opposite' },
              { kind: 'fill', sentence: 'Go ___ for two blocks.', choices: ['straight', 'left', 'far'], answer: 'straight' },
              { kind: 'fill', sentence: 'Excuse me, ___ is the bank?', choices: ['where', 'what', 'who'], answer: 'where' },
              { kind: 'order', words: ['Turn', 'left', 'at', 'the', 'traffic', 'lights'], answer: 'Turn left at the traffic lights' },
              { kind: 'listen', text: 'The pharmacy is on the corner.', options: ['The pharmacy is on the corner.', 'The pharmacy is opposite the corner.', 'The bakery is on the corner.'], answer: 'The pharmacy is on the corner.' },
            ],
          },
          {
            id: 'adults_u1_l3',
            emoji: '💼',
            titleEn: 'Small Talk at Work',
            titleVi: 'Trò chuyện nơi công sở',
            vocab: [
              { term: 'weekend', meaningVi: 'cuối tuần', example: 'How was your weekend?' },
              { term: 'weather', meaningVi: 'thời tiết', example: "Lovely weather today, isn't it?" },
              { term: 'meeting', meaningVi: 'cuộc họp', example: 'I have a meeting at ten.' },
              { term: 'project', meaningVi: 'dự án', example: 'The new project starts on Monday.' },
              { term: 'traffic', meaningVi: 'giao thông', example: 'The traffic was terrible this morning.' },
              { term: 'plan', meaningVi: 'kế hoạch', example: 'Do you have any plans for the holiday?' },
            ],
            grammar: {
              titleEn: 'Small-talk questions',
              titleVi: 'Câu hỏi xã giao',
              bodyEn: 'Friendly questions: How was…? What do you think of…? Did you…?',
              bodyVi: 'Câu hỏi xã giao thân thiện: How was…? (…thế nào?), What do you think of…? (Bạn thấy… sao?), Did you…? (Bạn đã… chưa?)',
              examples: [
                { en: 'How was your weekend?', vi: 'Cuối tuần của bạn thế nào?' },
                { en: 'Did you watch the match last night?', vi: 'Tối qua bạn có xem trận đấu không?' },
                { en: 'What do you think of the new project?', vi: 'Bạn thấy dự án mới thế nào?' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Câu mở đầu xã giao phù hợp nơi công sở:', options: ['How was your weekend?', 'How old are you?', 'How much money do you make?', 'Why are you late?'], answer: 'How was your weekend?' },
              { kind: 'mc', question: "'Cuộc họp' trong tiếng Anh là gì?", options: ['meeting', 'greeting', 'eating', 'seating'], answer: 'meeting' },
              { kind: 'fill', sentence: 'The ___ was terrible this morning.', choices: ['traffic', 'weather', 'weekend'], answer: 'traffic' },
              { kind: 'fill', sentence: '___ you watch the match last night?', choices: ['Did', 'Do', 'Does'], answer: 'Did' },
              { kind: 'order', words: ['How', 'was', 'your', 'weekend'], answer: 'How was your weekend' },
              { kind: 'listen', text: 'I have a meeting at ten.', options: ['I have a meeting at ten.', 'I have a meeting at two.', 'I had a meeting at ten.'], answer: 'I have a meeting at ten.' },
            ],
          },
        ],
      },
      {
        id: 'adults_u2',
        titleEn: 'Work & Life',
        titleVi: 'Công việc & Cuộc sống',
        lessons: [
          {
            id: 'adults_u2_l1',
            emoji: '📞',
            titleEn: 'On the Phone',
            titleVi: 'Nghe gọi điện thoại',
            vocab: [
              { term: 'call back', meaningVi: 'gọi lại', example: 'Could you call back later?' },
              { term: 'hold on', meaningVi: 'giữ máy', example: 'Hold on a moment, please.' },
              { term: 'speak up', meaningVi: 'nói to hơn', example: 'Could you speak up? The line is bad.' },
              { term: 'voicemail', meaningVi: 'hộp thư thoại', example: 'Please leave a voicemail.' },
              { term: 'available', meaningVi: 'rảnh / có mặt', example: 'Ms. Lan is not available right now.' },
              { term: 'wrong number', meaningVi: 'nhầm số', example: 'Sorry, you have the wrong number.' },
            ],
            grammar: {
              titleEn: 'Polite requests',
              titleVi: 'Yêu cầu lịch sự',
              bodyEn: 'On the phone, ask politely: Could you…? Would you mind + V-ing…? May I…?',
              bodyVi: 'Khi nghe gọi điện thoại, hãy yêu cầu lịch sự: Could you…? (Bạn có thể…?), Would you mind + V-ing…? (Bạn có phiền…?), May I…? (Tôi có thể…?)',
              examples: [
                { en: 'Could you call back after lunch?', vi: 'Bạn gọi lại sau giờ trưa được không?' },
                { en: 'Would you mind holding on a moment?', vi: 'Bạn vui lòng giữ máy một lát nhé?' },
                { en: "May I ask who's calling?", vi: 'Xin hỏi ai đang gọi ạ?' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'Cách yêu cầu lịch sự nhất qua điện thoại:', options: ['Could you call back later?', 'Call back later.', 'You must call back.', 'Call me!'], answer: 'Could you call back later?' },
              { kind: 'mc', question: "'Giữ máy' trong tiếng Anh là gì?", options: ['hold on', 'speak up', 'call back', 'hang up'], answer: 'hold on' },
              { kind: 'fill', sentence: 'Please leave a ___ after the beep.', choices: ['voicemail', 'ticket', 'meeting'], answer: 'voicemail' },
              { kind: 'fill', sentence: 'Would you mind ___ on a moment?', choices: ['holding', 'hold', 'held'], answer: 'holding' },
              { kind: 'order', words: ['May', 'I', 'ask', 'who', 'is', 'calling'], answer: 'May I ask who is calling' },
              { kind: 'listen', text: 'Ms. Lan is not available right now.', options: ['Ms. Lan is not available right now.', 'Ms. Lan is available right now.', 'Mr. Nam is not available right now.'], answer: 'Ms. Lan is not available right now.' },
            ],
          },
          {
            id: 'adults_u2_l2',
            emoji: '🛍️',
            titleEn: 'Shopping',
            titleVi: 'Đi mua sắm',
            vocab: [
              { term: 'discount', meaningVi: 'giảm giá', example: 'Is there a discount today?' },
              { term: 'size', meaningVi: 'cỡ', example: 'Do you have this in size M?' },
              { term: 'fitting room', meaningVi: 'phòng thử đồ', example: 'Where is the fitting room?' },
              { term: 'receipt', meaningVi: 'biên nhận', example: 'Keep your receipt, please.' },
              { term: 'refund', meaningVi: 'hoàn tiền', example: 'Can I get a refund?' },
              { term: 'try on', meaningVi: 'mặc thử', example: 'Can I try on this shirt?' },
            ],
            grammar: {
              titleEn: 'too / enough',
              titleVi: 'too / enough (quá / đủ)',
              bodyEn: "too + adjective = excessively (too small); adjective + enough = sufficiently (big enough).",
              bodyVi: 'too + tính từ = quá (too small: quá nhỏ); tính từ + enough = đủ (big enough: đủ rộng).',
              examples: [
                { en: 'This shirt is too small.', vi: 'Cái áo này quá nhỏ.' },
                { en: 'Is it big enough?', vi: 'Nó đủ rộng không?' },
                { en: 'The price is too high.', vi: 'Giá quá cao.' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'This shirt is ___ small. (quá nhỏ)', options: ['too', 'enough', 'more', 'much'], answer: 'too' },
              { kind: 'mc', question: "'Hoàn tiền' trong tiếng Anh là gì?", options: ['refund', 'receipt', 'discount', 'size'], answer: 'refund' },
              { kind: 'fill', sentence: 'Where is the ___ room?', choices: ['fitting', 'sitting', 'waiting'], answer: 'fitting' },
              { kind: 'fill', sentence: 'Is this jacket big ___?', choices: ['enough', 'too', 'more'], answer: 'enough' },
              { kind: 'order', words: ['Can', 'I', 'try', 'on', 'this', 'shirt'], answer: 'Can I try on this shirt' },
              { kind: 'listen', text: 'Is there a discount today?', options: ['Is there a discount today?', 'Is there a disco today?', 'Was there a discount yesterday?'], answer: 'Is there a discount today?' },
            ],
          },
          {
            id: 'adults_u2_l3',
            emoji: '🩺',
            titleEn: 'At the Doctor',
            titleVi: 'Đi khám bệnh',
            vocab: [
              { term: 'headache', meaningVi: 'đau đầu', example: 'I have a terrible headache.' },
              { term: 'fever', meaningVi: 'sốt', example: 'She has a high fever.' },
              { term: 'appointment', meaningVi: 'lịch hẹn', example: "I'd like to make an appointment." },
              { term: 'prescription', meaningVi: 'đơn thuốc', example: 'Take this prescription to the pharmacy.' },
              { term: 'pharmacy', meaningVi: 'nhà thuốc', example: 'The pharmacy is open until 9 p.m.' },
              { term: 'rest', meaningVi: 'nghỉ ngơi', example: 'You should rest for a few days.' },
            ],
            grammar: {
              titleEn: "should / shouldn't",
              titleVi: "should / shouldn't (nên / không nên)",
              bodyEn: "Give advice with should (you should rest) and shouldn't (you shouldn't work late).",
              bodyVi: "Khuyên nhủ với should (nên): You should rest (bạn nên nghỉ ngơi) và shouldn't (không nên): You shouldn't work late.",
              examples: [
                { en: 'You should drink more water.', vi: 'Bạn nên uống nhiều nước hơn.' },
                { en: "You shouldn't skip breakfast.", vi: 'Bạn không nên bỏ bữa sáng.' },
                { en: 'Should I take this medicine after meals?', vi: 'Tôi nên uống thuốc này sau bữa ăn phải không?' },
              ],
            },
            exercises: [
              { kind: 'mc', question: 'You ___ rest for a few days. (nên)', options: ['should', "shouldn't", 'must not', "can't"], answer: 'should' },
              { kind: 'mc', question: "'Đơn thuốc' trong tiếng Anh là gì?", options: ['prescription', 'subscription', 'description', 'reception'], answer: 'prescription' },
              { kind: 'fill', sentence: 'I have a terrible ___.', choices: ['headache', 'pharmacy', 'appointment'], answer: 'headache' },
              { kind: 'fill', sentence: 'You ___ work late when you are sick. (không nên)', choices: ["shouldn't", 'should', 'can'], answer: "shouldn't" },
              { kind: 'order', words: ['I', 'would', 'like', 'to', 'make', 'an', 'appointment'], answer: 'I would like to make an appointment' },
              { kind: 'listen', text: 'She has a high fever.', options: ['She has a high fever.', 'She has a high fee.', 'He has a high fever.'], answer: 'She has a high fever.' },
            ],
          },
        ],
      },
    ],
  },
];

export function allLessons(course: Course) {
  return course.units.flatMap((u) => u.lessons);
}

export function recommendedCourse(classLevels: string[]): Course {
  for (const course of COURSES) {
    if (classLevels.some((lv) => course.levelKeywords.some((k) => lv.includes(k)))) return course;
  }
  return COURSES[1]; // teens as a sensible default
}
