import type { Course, Exercise, Lesson } from './types';

// "English Foundations" — a 20-level path from absolute beginner (Level 1)
// to low-intermediate (Level 20), for anyone starting English from zero.

type V = [term: string, meaningVi: string, example: string];
type G = [titleEn: string, titleVi: string, bodyEn: string, bodyVi: string, examples: [en: string, vi: string][]];

function L(num: number, emoji: string, titleEn: string, titleVi: string, vocab: V[], g: G, exercises: Exercise[]): Lesson {
  return {
    id: `found_l${num}`,
    emoji,
    titleEn: `Level ${num}: ${titleEn}`,
    titleVi: `Cấp ${num}: ${titleVi}`,
    vocab: vocab.map(([term, meaningVi, example]) => ({ term, meaningVi, example })),
    grammar: { titleEn: g[0], titleVi: g[1], bodyEn: g[2], bodyVi: g[3], examples: g[4].map(([en, vi]) => ({ en, vi })) },
    exercises,
  };
}

const LESSONS: Lesson[] = [
  L(1, '🔤', 'First Words', 'Những từ đầu tiên',
    [
      ['hello', 'xin chào', 'Hello! How are you?'],
      ['yes', 'vâng / có', 'Yes, please.'],
      ['no', 'không', 'No, thank you.'],
      ['please', 'làm ơn / vui lòng', 'One coffee, please.'],
      ['thank you', 'cảm ơn', 'Thank you very much!'],
    ],
    ['Hello, I am…', 'Hello, I am…', "Your very first sentence: Hello, I am + your name.", 'Câu tiếng Anh đầu tiên của bạn: Hello, I am + tên (Xin chào, tôi là…).',
      [['Hello, I am An.', 'Xin chào, tôi là An.'], ['Nice to meet you.', 'Rất vui được gặp bạn.'], ['Thank you very much.', 'Cảm ơn bạn rất nhiều.']]],
    [
      { kind: 'mc', question: "'Cảm ơn' trong tiếng Anh là gì?", options: ['thank you', 'please', 'hello', 'yes'], answer: 'thank you' },
      { kind: 'mc', question: 'Hello, I ___ An.', options: ['am', 'is', 'are', 'be'], answer: 'am' },
      { kind: 'fill', sentence: 'One coffee, ___.', choices: ['please', 'yes', 'hello'], answer: 'please' },
      { kind: 'fill', sentence: '___, thank you. (không)', choices: ['No', 'Yes', 'Please'], answer: 'No' },
      { kind: 'order', words: ['Hello', 'I', 'am', 'An'], answer: 'Hello I am An' },
      { kind: 'listen', text: 'Nice to meet you.', options: ['Nice to meet you.', 'Nice to see you.', 'Nice to feed you.'], answer: 'Nice to meet you.' },
    ]),
  L(2, '🔢', 'Numbers & Age', 'Con số & Tuổi',
    [
      ['one', 'số một', 'I have one brother.'],
      ['three', 'số ba', 'She has three pens.'],
      ['five', 'số năm', 'There are five books.'],
      ['old', 'tuổi', 'How old are you?'],
      ['year', 'năm', 'I am ten years old.'],
    ],
    ['How old are you?', 'How old are you? (Bạn bao nhiêu tuổi?)', 'Ask age with How old are you? Answer: I am + number + years old.', 'Hỏi tuổi: How old are you? Trả lời: I am + số + years old (tôi … tuổi).',
      [['How old are you?', 'Bạn bao nhiêu tuổi?'], ['I am twelve years old.', 'Tôi mười hai tuổi.'], ['My sister is five.', 'Em gái tôi năm tuổi.']]],
    [
      { kind: 'mc', question: "'Số năm' trong tiếng Anh là gì?", options: ['five', 'four', 'nine', 'ten'], answer: 'five' },
      { kind: 'mc', question: 'How old ___ you?', options: ['are', 'is', 'am', 'be'], answer: 'are' },
      { kind: 'fill', sentence: 'I am ten ___ old.', choices: ['years', 'days', 'names'], answer: 'years' },
      { kind: 'fill', sentence: 'She has ___ pens. (3)', choices: ['three', 'tree', 'third'], answer: 'three' },
      { kind: 'order', words: ['How', 'old', 'are', 'you'], answer: 'How old are you' },
      { kind: 'listen', text: 'I am twelve years old.', options: ['I am twelve years old.', 'I am twenty years old.', 'I am seven years old.'], answer: 'I am twelve years old.' },
    ]),
  L(3, '🌏', 'Where Are You From?', 'Bạn đến từ đâu?',
    [
      ['country', 'đất nước', 'Vietnam is a beautiful country.'],
      ['from', 'từ / đến từ', 'I am from Phan Thiet.'],
      ['city', 'thành phố', 'Da Nang is a big city.'],
      ['live', 'sống', 'I live in Binh Thuan.'],
      ['Vietnamese', 'người / tiếng Việt', 'I am Vietnamese.'],
    ],
    ['I am from…', 'I am from… (Tôi đến từ…)', 'Say your country or city with I am from… and where you live with I live in…', 'Nói quê quán với I am from… (tôi đến từ…) và nơi ở với I live in… (tôi sống ở…).',
      [['I am from Vietnam.', 'Tôi đến từ Việt Nam.'], ['Where are you from?', 'Bạn đến từ đâu?'], ['I live in Phan Thiet.', 'Tôi sống ở Phan Thiết.']]],
    [
      { kind: 'mc', question: "'Đất nước' trong tiếng Anh là gì?", options: ['country', 'city', 'county', 'court'], answer: 'country' },
      { kind: 'mc', question: 'Where are you ___?', options: ['from', 'live', 'in', 'at'], answer: 'from' },
      { kind: 'fill', sentence: 'I ___ in Binh Thuan.', choices: ['live', 'from', 'old'], answer: 'live' },
      { kind: 'fill', sentence: 'I am ___ Vietnam.', choices: ['from', 'in', 'old'], answer: 'from' },
      { kind: 'order', words: ['I', 'am', 'from', 'Vietnam'], answer: 'I am from Vietnam' },
      { kind: 'listen', text: 'I live in Phan Thiet.', options: ['I live in Phan Thiet.', 'I leave Phan Thiet.', 'I live in Da Lat.'], answer: 'I live in Phan Thiet.' },
    ]),
  L(4, '🏫', 'The Classroom', 'Trong lớp học',
    [
      ['classroom', 'phòng học', 'Our classroom is bright.'],
      ['desk', 'bàn học', 'My books are on the desk.'],
      ['chair', 'ghế', 'Please sit on the chair.'],
      ['board', 'bảng', 'Look at the board, please.'],
      ['listen', 'nghe', 'Listen and repeat.'],
    ],
    ['This is / That is', 'This is / That is (Đây là / Kia là)', 'Use this for near things and that for far things: This is my desk. That is the board.', 'Dùng this cho vật ở gần (đây là) và that cho vật ở xa (kia là): This is my desk. That is the board.',
      [['This is my desk.', 'Đây là bàn của tôi.'], ['That is the board.', 'Kia là cái bảng.'], ['Open your book, please.', 'Mở sách ra nhé.']]],
    [
      { kind: 'mc', question: "'Bảng' trong tiếng Anh là gì?", options: ['board', 'desk', 'chair', 'book'], answer: 'board' },
      { kind: 'mc', question: 'Vật ở xa dùng từ nào?', options: ['that', 'this', 'these', 'here'], answer: 'that' },
      { kind: 'fill', sentence: 'Please sit on the ___.', choices: ['chair', 'board', 'listen'], answer: 'chair' },
      { kind: 'fill', sentence: '___ is my desk. (đây)', choices: ['This', 'That', 'It'], answer: 'This' },
      { kind: 'order', words: ['Look', 'at', 'the', 'board', 'please'], answer: 'Look at the board please' },
      { kind: 'listen', text: 'Listen and repeat.', options: ['Listen and repeat.', 'Listen and read.', 'Sit and repeat.'], answer: 'Listen and repeat.' },
    ]),
  L(5, '🧸', 'My Things', 'Đồ của tôi',
    [
      ['phone', 'điện thoại', 'My phone is new.'],
      ['key', 'chìa khóa', 'Where are my keys?'],
      ['bottle', 'chai nước', 'This is my water bottle.'],
      ['wallet', 'ví tiền', 'His wallet is black.'],
      ['umbrella', 'cái ô / dù', 'Take an umbrella today.'],
    ],
    ['my / your / his / her', 'Tính từ sở hữu', 'my = of me, your = of you, his = of him, her = of her: Her phone is new.', 'my (của tôi), your (của bạn), his (của anh ấy), her (của cô ấy): Her phone is new (điện thoại của cô ấy mới).',
      [['My phone is new.', 'Điện thoại của tôi mới.'], ['Is this your key?', 'Đây là chìa khóa của bạn à?'], ['His wallet is black.', 'Ví của anh ấy màu đen.']]],
    [
      { kind: 'mc', question: "'Chìa khóa' trong tiếng Anh là gì?", options: ['key', 'wallet', 'phone', 'bottle'], answer: 'key' },
      { kind: 'mc', question: "'Của cô ấy' dùng từ nào?", options: ['her', 'his', 'my', 'your'], answer: 'her' },
      { kind: 'fill', sentence: 'Is this ___ key? (của bạn)', choices: ['your', 'my', 'his'], answer: 'your' },
      { kind: 'fill', sentence: 'Take an ___ today.', choices: ['umbrella', 'wallet', 'key'], answer: 'umbrella' },
      { kind: 'order', words: ['His', 'wallet', 'is', 'black'], answer: 'His wallet is black' },
      { kind: 'listen', text: 'Where are my keys?', options: ['Where are my keys?', 'Where are my kids?', 'Where is my key?'], answer: 'Where are my keys?' },
    ]),
  L(6, '👪', 'Family & Friends', 'Gia đình & Bạn bè',
    [
      ['parents', 'bố mẹ', 'My parents work in the city.'],
      ['children', 'con cái / trẻ em', 'They have two children.'],
      ['husband', 'chồng', 'Her husband is a teacher.'],
      ['wife', 'vợ', 'His wife cooks very well.'],
      ['younger', 'nhỏ hơn / em', 'My younger brother is six.'],
    ],
    ["Possessive 's", "Sở hữu cách 's", "Add 's to a person to show possession: Lan's father, my friend's house.", "Thêm 's sau tên người để chỉ sở hữu: Lan's father (bố của Lan), my friend's house (nhà của bạn tôi).",
      [["Lan's father is a doctor.", 'Bố của Lan là bác sĩ.'], ["This is my friend's house.", 'Đây là nhà của bạn tôi.'], ["My parents' room is big.", 'Phòng của bố mẹ tôi rộng.']]],
    [
      { kind: 'mc', question: "'Bố mẹ' trong tiếng Anh là gì?", options: ['parents', 'children', 'cousins', 'friends'], answer: 'parents' },
      { kind: 'mc', question: "'Bố của Lan' viết thế nào?", options: ["Lan's father", 'Lan father', "Lans' father", 'father Lan'], answer: "Lan's father" },
      { kind: 'fill', sentence: 'They have two ___.', choices: ['children', 'childs', 'parents'], answer: 'children' },
      { kind: 'fill', sentence: 'Her ___ is a teacher. (chồng)', choices: ['husband', 'wife', 'brother'], answer: 'husband' },
      { kind: 'order', words: ['My', 'younger', 'brother', 'is', 'six'], answer: 'My younger brother is six' },
      { kind: 'listen', text: 'His wife cooks very well.', options: ['His wife cooks very well.', 'His wife cooks very fast.', 'His wife looks very well.'], answer: 'His wife cooks very well.' },
    ]),
  L(7, '😊', 'Describing People', 'Miêu tả con người',
    [
      ['tall', 'cao', 'My father is very tall.'],
      ['short', 'thấp / ngắn', 'She has short hair.'],
      ['kind', 'tốt bụng', 'Our teacher is kind.'],
      ['funny', 'vui tính', 'My best friend is funny.'],
      ['smart', 'thông minh', 'You are very smart!'],
    ],
    ['be + adjective', 'be + tính từ', 'Describe people with am/is/are + adjective: She is kind. They are tall.', 'Miêu tả người với am/is/are + tính từ: She is kind (cô ấy tốt bụng). They are tall (họ cao).',
      [['She is kind.', 'Cô ấy tốt bụng.'], ['They are tall.', 'Họ cao.'], ['Am I funny?', 'Tôi có vui tính không?']]],
    [
      { kind: 'mc', question: "'Thông minh' trong tiếng Anh là gì?", options: ['smart', 'small', 'short', 'start'], answer: 'smart' },
      { kind: 'mc', question: 'They ___ tall.', options: ['are', 'is', 'am', 'be'], answer: 'are' },
      { kind: 'fill', sentence: 'She has ___ hair.', choices: ['short', 'kind', 'funny'], answer: 'short' },
      { kind: 'fill', sentence: 'Our teacher ___ kind.', choices: ['is', 'are', 'am'], answer: 'is' },
      { kind: 'order', words: ['My', 'best', 'friend', 'is', 'funny'], answer: 'My best friend is funny' },
      { kind: 'listen', text: 'My father is very tall.', options: ['My father is very tall.', 'My father is very old.', 'My brother is very tall.'], answer: 'My father is very tall.' },
    ]),
  L(8, '🏠', 'My House', 'Ngôi nhà của tôi',
    [
      ['kitchen', 'nhà bếp', 'Mom is cooking in the kitchen.'],
      ['bedroom', 'phòng ngủ', 'My bedroom is small but cozy.'],
      ['bathroom', 'phòng tắm', 'The bathroom is upstairs.'],
      ['garden', 'khu vườn', 'There are flowers in the garden.'],
      ['window', 'cửa sổ', 'Open the window, please.'],
    ],
    ['There is / There are', 'There is / There are (Có…)', "There is + one thing, There are + many things: There is a garden. There are two bedrooms.", 'There is + một vật, There are + nhiều vật: There is a garden (có một khu vườn). There are two bedrooms (có hai phòng ngủ).',
      [['There is a big kitchen.', 'Có một nhà bếp lớn.'], ['There are two bedrooms.', 'Có hai phòng ngủ.'], ['Is there a garden? — Yes, there is.', 'Có vườn không? — Có.']]],
    [
      { kind: 'mc', question: "'Nhà bếp' trong tiếng Anh là gì?", options: ['kitchen', 'chicken', 'bedroom', 'bathroom'], answer: 'kitchen' },
      { kind: 'mc', question: '___ two bedrooms in my house.', options: ['There are', 'There is', 'They are', 'It is'], answer: 'There are' },
      { kind: 'fill', sentence: 'Open the ___, please.', choices: ['window', 'garden', 'kitchen'], answer: 'window' },
      { kind: 'fill', sentence: 'There ___ a garden behind the house.', choices: ['is', 'are', 'am'], answer: 'is' },
      { kind: 'order', words: ['There', 'are', 'flowers', 'in', 'the', 'garden'], answer: 'There are flowers in the garden' },
      { kind: 'listen', text: 'The bathroom is upstairs.', options: ['The bathroom is upstairs.', 'The bedroom is upstairs.', 'The bathroom is downstairs.'], answer: 'The bathroom is upstairs.' },
    ]),
  L(9, '☀️', 'Every Morning', 'Mỗi buổi sáng',
    [
      ['get up', 'thức dậy', 'I get up at six.'],
      ['brush', 'đánh (răng) / chải', 'I brush my teeth twice a day.'],
      ['wash', 'rửa', 'Wash your hands before lunch.'],
      ['get dressed', 'mặc quần áo', 'I get dressed quickly.'],
      ['leave', 'rời đi', 'We leave home at seven.'],
    ],
    ['Present simple (I/you/we)', 'Hiện tại đơn (I/you/we)', 'For daily habits use the base verb: I get up at six. We leave at seven.', 'Nói thói quen hằng ngày với động từ nguyên mẫu: I get up at six (tôi dậy lúc 6 giờ). We leave at seven.',
      [['I get up at six.', 'Tôi thức dậy lúc sáu giờ.'], ['We leave home at seven.', 'Chúng tôi ra khỏi nhà lúc bảy giờ.'], ['You brush your teeth every day.', 'Bạn đánh răng mỗi ngày.']]],
    [
      { kind: 'mc', question: "'Thức dậy' trong tiếng Anh là gì?", options: ['get up', 'get dressed', 'wash', 'leave'], answer: 'get up' },
      { kind: 'mc', question: 'I ___ my teeth twice a day.', options: ['brush', 'wash', 'leave', 'dress'], answer: 'brush' },
      { kind: 'fill', sentence: '___ your hands before lunch.', choices: ['Wash', 'Brush', 'Leave'], answer: 'Wash' },
      { kind: 'fill', sentence: 'We ___ home at seven.', choices: ['leave', 'get', 'wash'], answer: 'leave' },
      { kind: 'order', words: ['I', 'get', 'up', 'at', 'six'], answer: 'I get up at six' },
      { kind: 'listen', text: 'I get dressed quickly.', options: ['I get dressed quickly.', 'I get dressed slowly.', 'I get up quickly.'], answer: 'I get dressed quickly.' },
    ]),
  L(10, '👩‍💼', 'Jobs & Work', 'Nghề nghiệp',
    [
      ['doctor', 'bác sĩ', 'My aunt is a doctor.'],
      ['farmer', 'nông dân', 'The farmer grows dragon fruit.'],
      ['driver', 'tài xế', 'The driver is very careful.'],
      ['nurse', 'y tá', 'The nurse helps the doctor.'],
      ['job', 'công việc', 'What is your job?'],
    ],
    ['He/She works…', 'Hiện tại đơn (he/she)', "With he/she/it add 's' or 'es' to the verb: She works in a hospital. He teaches English.", "Với he/she/it, thêm 's' hoặc 'es' vào động từ: She works in a hospital (cô ấy làm ở bệnh viện). He teaches English.",
      [['She works in a hospital.', 'Cô ấy làm việc ở bệnh viện.'], ['He drives a bus.', 'Anh ấy lái xe buýt.'], ['My father grows dragon fruit.', 'Bố tôi trồng thanh long.']]],
    [
      { kind: 'mc', question: "'Y tá' trong tiếng Anh là gì?", options: ['nurse', 'doctor', 'driver', 'farmer'], answer: 'nurse' },
      { kind: 'mc', question: 'She ___ in a hospital.', options: ['works', 'work', 'working', 'worked'], answer: 'works' },
      { kind: 'fill', sentence: 'What is your ___?', choices: ['job', 'work', 'doctor'], answer: 'job' },
      { kind: 'fill', sentence: 'He ___ a bus every day.', choices: ['drives', 'drive', 'driving'], answer: 'drives' },
      { kind: 'order', words: ['My', 'aunt', 'is', 'a', 'doctor'], answer: 'My aunt is a doctor' },
      { kind: 'listen', text: 'The farmer grows dragon fruit.', options: ['The farmer grows dragon fruit.', 'The farmer grows watermelon.', 'The father grows dragon fruit.'], answer: 'The farmer grows dragon fruit.' },
    ]),
  L(11, '🕐', 'Telling the Time', 'Xem giờ',
    [
      ["o'clock", 'giờ (đúng)', "It is eight o'clock."],
      ['half past', 'rưỡi (giờ rưỡi)', 'The class starts at half past five.'],
      ['early', 'sớm', 'I get up early on Mondays.'],
      ['late', 'muộn / trễ', "Don't be late for class!"],
      ['weekend', 'cuối tuần', 'I relax at the weekend.'],
    ],
    ['at / in / on (time)', 'Giới từ thời gian at / in / on', 'at + clock time (at 5:30), on + days (on Monday), in + parts of day (in the morning).', 'at + giờ (at 5:30), on + thứ/ngày (on Monday), in + buổi (in the morning: vào buổi sáng).',
      [['The class starts at half past five.', 'Lớp học bắt đầu lúc năm giờ rưỡi.'], ['We study English on Tuesdays.', 'Chúng tôi học tiếng Anh vào thứ Ba.'], ['I do homework in the evening.', 'Tôi làm bài tập vào buổi tối.']]],
    [
      { kind: 'mc', question: 'We study English ___ Tuesdays.', options: ['on', 'at', 'in', 'to'], answer: 'on' },
      { kind: 'mc', question: "'Muộn' trong tiếng Anh là gì?", options: ['late', 'early', 'fast', 'slow'], answer: 'late' },
      { kind: 'fill', sentence: 'The class starts ___ half past five.', choices: ['at', 'on', 'in'], answer: 'at' },
      { kind: 'fill', sentence: 'I do homework ___ the evening.', choices: ['in', 'at', 'on'], answer: 'in' },
      { kind: 'order', words: ['It', 'is', 'eight', "o'clock"], answer: "It is eight o'clock" },
      { kind: 'listen', text: "Don't be late for class!", options: ["Don't be late for class!", "Don't be lazy in class!", 'Do be late for class!'], answer: "Don't be late for class!" },
    ]),
  L(12, '🍜', 'Food: Some & Any', 'Đồ ăn: some & any',
    [
      ['bread', 'bánh mì', 'We need some bread.'],
      ['egg', 'trứng', 'I eat two eggs for breakfast.'],
      ['sugar', 'đường', 'No sugar in my coffee, please.'],
      ['fruit', 'trái cây', 'Eat more fruit every day.'],
      ['hungry', 'đói', 'I am so hungry!'],
    ],
    ['some / any', 'some / any (một ít / chút nào)', "some in positive sentences (some bread), any in questions and negatives (any eggs? / not any sugar).", 'some dùng trong câu khẳng định (some bread: một ít bánh mì), any trong câu hỏi và phủ định (Do we have any eggs? / There is not any sugar).',
      [['We need some bread.', 'Chúng ta cần một ít bánh mì.'], ['Do we have any eggs?', 'Nhà mình còn quả trứng nào không?'], ['There is not any sugar.', 'Không còn chút đường nào.']]],
    [
      { kind: 'mc', question: 'We need ___ bread. (khẳng định)', options: ['some', 'any', 'a', 'an'], answer: 'some' },
      { kind: 'mc', question: 'Do we have ___ eggs? (câu hỏi)', options: ['any', 'some', 'much', 'a'], answer: 'any' },
      { kind: 'fill', sentence: 'No ___ in my coffee, please.', choices: ['sugar', 'bread', 'fruit'], answer: 'sugar' },
      { kind: 'fill', sentence: 'I am so ___!', choices: ['hungry', 'angry', 'early'], answer: 'hungry' },
      { kind: 'order', words: ['Eat', 'more', 'fruit', 'every', 'day'], answer: 'Eat more fruit every day' },
      { kind: 'listen', text: 'I eat two eggs for breakfast.', options: ['I eat two eggs for breakfast.', 'I eat two eggs for dinner.', 'I need two eggs for breakfast.'], answer: 'I eat two eggs for breakfast.' },
    ]),
  L(13, '🛒', 'At the Market', 'Ở chợ',
    [
      ['How much', 'bao nhiêu (giá/không đếm được)', 'How much is this fish?'],
      ['How many', 'bao nhiêu (đếm được)', 'How many mangoes do you want?'],
      ['kilo', 'cân / kí', 'A kilo of rice, please.'],
      ['cheap', 'rẻ', 'Vegetables are cheap today.'],
      ['expensive', 'đắt', 'That fish is too expensive!'],
    ],
    ['How much / How many', 'How much / How many', 'How many + countable nouns (mangoes), How much + uncountable nouns and prices.', 'How many + danh từ đếm được (mangoes: mấy quả xoài), How much + danh từ không đếm được và giá tiền (How much is it?: bao nhiêu tiền?).',
      [['How much is this fish?', 'Con cá này bao nhiêu tiền?'], ['How many mangoes do you want?', 'Bạn muốn mấy quả xoài?'], ['A kilo of rice, please.', 'Cho một cân gạo ạ.']]],
    [
      { kind: 'mc', question: '___ mangoes do you want?', options: ['How many', 'How much', 'How old', 'How far'], answer: 'How many' },
      { kind: 'mc', question: "'Đắt' trong tiếng Anh là gì?", options: ['expensive', 'cheap', 'delicious', 'heavy'], answer: 'expensive' },
      { kind: 'fill', sentence: '___ much is this fish?', choices: ['How', 'What', 'Who'], answer: 'How' },
      { kind: 'fill', sentence: 'Vegetables are ___ today. (rẻ)', choices: ['cheap', 'expensive', 'hungry'], answer: 'cheap' },
      { kind: 'order', words: ['A', 'kilo', 'of', 'rice', 'please'], answer: 'A kilo of rice please' },
      { kind: 'listen', text: 'That fish is too expensive!', options: ['That fish is too expensive!', 'That fish is too delicious!', 'That dish is too expensive!'], answer: 'That fish is too expensive!' },
    ]),
  L(14, '👕', 'Right Now', 'Ngay lúc này',
    [
      ['wear', 'mặc', 'She is wearing a blue dress.'],
      ['wait', 'chờ / đợi', 'We are waiting for the bus.'],
      ['rain', 'mưa', 'Look! It is raining.'],
      ['cook', 'nấu ăn', 'Dad is cooking dinner now.'],
      ['study', 'học', 'They are studying for the exam.'],
    ],
    ['Present continuous', 'Hiện tại tiếp diễn', 'For actions happening now: am/is/are + V-ing. She is wearing a dress. It is raining.', 'Diễn tả việc đang xảy ra: am/is/are + V-ing. She is wearing a dress (cô ấy đang mặc váy). It is raining (trời đang mưa).',
      [['She is wearing a blue dress.', 'Cô ấy đang mặc váy xanh.'], ['It is raining now.', 'Trời đang mưa.'], ['What are you doing?', 'Bạn đang làm gì vậy?']]],
    [
      { kind: 'mc', question: 'Look! It ___ raining.', options: ['is', 'are', 'am', 'be'], answer: 'is' },
      { kind: 'mc', question: 'What are you ___?', options: ['doing', 'do', 'does', 'did'], answer: 'doing' },
      { kind: 'fill', sentence: 'Dad is ___ dinner now.', choices: ['cooking', 'cook', 'cooks'], answer: 'cooking' },
      { kind: 'fill', sentence: 'We are ___ for the bus.', choices: ['waiting', 'wait', 'waits'], answer: 'waiting' },
      { kind: 'order', words: ['They', 'are', 'studying', 'for', 'the', 'exam'], answer: 'They are studying for the exam' },
      { kind: 'listen', text: 'She is wearing a blue dress.', options: ['She is wearing a blue dress.', 'She is washing a blue dress.', 'She is wearing a new dress.'], answer: 'She is wearing a blue dress.' },
    ]),
  L(15, '⚖️', 'Now vs Every Day', 'Đang làm vs Hằng ngày',
    [
      ['usually', 'thường', 'I usually walk to school.'],
      ['today', 'hôm nay', 'Today I am taking the bus.'],
      ['now', 'bây giờ', 'I am busy now.'],
      ['every day', 'mỗi ngày', 'She practices English every day.'],
      ['at the moment', 'ngay lúc này', 'He is sleeping at the moment.'],
    ],
    ['Simple vs Continuous', 'Hiện tại đơn vs Tiếp diễn', 'Habits → present simple (I usually walk). Happening now → continuous (Today I am taking the bus).', 'Thói quen → hiện tại đơn (I usually walk: tôi thường đi bộ). Đang xảy ra → tiếp diễn (Today I am taking the bus: hôm nay tôi đang đi xe buýt).',
      [['I usually walk to school.', 'Tôi thường đi bộ đến trường.'], ['Today I am taking the bus.', 'Hôm nay tôi đi xe buýt.'], ['He is sleeping at the moment.', 'Anh ấy đang ngủ ngay lúc này.']]],
    [
      { kind: 'mc', question: 'I usually ___ to school.', options: ['walk', 'walking', 'am walking', 'walks'], answer: 'walk' },
      { kind: 'mc', question: 'Today I ___ the bus.', options: ['am taking', 'take', 'takes', 'taking'], answer: 'am taking' },
      { kind: 'fill', sentence: 'She practices English ___ day.', choices: ['every', 'now', 'today'], answer: 'every' },
      { kind: 'fill', sentence: 'He is sleeping at the ___.', choices: ['moment', 'morning', 'minute'], answer: 'moment' },
      { kind: 'order', words: ['I', 'am', 'busy', 'now'], answer: 'I am busy now' },
      { kind: 'listen', text: 'She practices English every day.', options: ['She practices English every day.', 'She practices English every Monday.', 'She teaches English every day.'], answer: 'She practices English every day.' },
    ]),
  L(16, '🏙️', 'Around Town', 'Quanh thành phố',
    [
      ['market', 'chợ', 'The market opens at five in the morning.'],
      ['hospital', 'bệnh viện', 'The hospital is next to the park.'],
      ['bank', 'ngân hàng', 'The bank closes at four.'],
      ['next to', 'bên cạnh', 'The café is next to the bookshop.'],
      ['behind', 'phía sau', 'The school is behind the market.'],
    ],
    ['Prepositions of place', 'Giới từ chỉ nơi chốn', 'next to (beside), behind, opposite, between — to say where places are.', 'next to (bên cạnh), behind (phía sau), opposite (đối diện), between (ở giữa) — để nói vị trí các địa điểm.',
      [['The hospital is next to the park.', 'Bệnh viện ở cạnh công viên.'], ['The school is behind the market.', 'Trường học ở phía sau chợ.'], ['The bank is between two shops.', 'Ngân hàng nằm giữa hai cửa hàng.']]],
    [
      { kind: 'mc', question: "'Bệnh viện' trong tiếng Anh là gì?", options: ['hospital', 'hotel', 'hostel', 'house'], answer: 'hospital' },
      { kind: 'mc', question: "'Phía sau' là từ nào?", options: ['behind', 'next to', 'between', 'opposite'], answer: 'behind' },
      { kind: 'fill', sentence: 'The café is ___ to the bookshop.', choices: ['next', 'behind', 'near'], answer: 'next' },
      { kind: 'fill', sentence: 'The bank ___ at four.', choices: ['closes', 'close', 'closing'], answer: 'closes' },
      { kind: 'order', words: ['The', 'school', 'is', 'behind', 'the', 'market'], answer: 'The school is behind the market' },
      { kind: 'listen', text: 'The market opens at five in the morning.', options: ['The market opens at five in the morning.', 'The market opens at nine in the morning.', 'The market closes at five in the morning.'], answer: 'The market opens at five in the morning.' },
    ]),
  L(17, '📅', 'Yesterday', 'Ngày hôm qua',
    [
      ['yesterday', 'hôm qua', 'Yesterday was Sunday.'],
      ['was / were', 'đã (là)', 'I was tired last night.'],
      ['visited', 'đã thăm', 'We visited my grandparents.'],
      ['watched', 'đã xem', 'I watched a great film.'],
      ['ago', 'trước đây', 'She called me an hour ago.'],
    ],
    ['Past simple (was/were, -ed)', 'Quá khứ đơn (was/were, -ed)', 'be → was/were. Regular verbs add -ed: visited, watched. I was tired. We visited Hue.', 'be → was/were (đã là). Động từ thường thêm -ed: visited (đã thăm), watched (đã xem). I was tired (tôi đã mệt).',
      [['I was tired last night.', 'Tối qua tôi mệt.'], ['We visited my grandparents.', 'Chúng tôi đã thăm ông bà.'], ['They were at the beach yesterday.', 'Hôm qua họ ở bãi biển.']]],
    [
      { kind: 'mc', question: 'I ___ tired last night.', options: ['was', 'were', 'am', 'is'], answer: 'was' },
      { kind: 'mc', question: 'They ___ at the beach yesterday.', options: ['were', 'was', 'are', 'be'], answer: 'were' },
      { kind: 'fill', sentence: 'We ___ my grandparents last weekend.', choices: ['visited', 'visit', 'visits'], answer: 'visited' },
      { kind: 'fill', sentence: 'She called me an hour ___.', choices: ['ago', 'late', 'now'], answer: 'ago' },
      { kind: 'order', words: ['I', 'watched', 'a', 'great', 'film'], answer: 'I watched a great film' },
      { kind: 'listen', text: 'Yesterday was Sunday.', options: ['Yesterday was Sunday.', 'Yesterday was sunny.', 'Tomorrow is Sunday.'], answer: 'Yesterday was Sunday.' },
    ]),
  L(18, '🧳', 'A Trip to Remember', 'Chuyến đi đáng nhớ',
    [
      ['went', 'đã đi', 'We went to Nha Trang last summer.'],
      ['saw', 'đã thấy / xem', 'I saw the sunrise at the beach.'],
      ['ate', 'đã ăn', 'We ate fresh seafood.'],
      ['took', 'đã chụp / lấy', 'She took a lot of photos.'],
      ['bought', 'đã mua', 'He bought souvenirs for everyone.'],
    ],
    ['Irregular past verbs', 'Động từ bất quy tắc', 'Many common verbs are irregular: go→went, see→saw, eat→ate, take→took, buy→bought.', 'Nhiều động từ thông dụng có dạng quá khứ bất quy tắc: go→went, see→saw, eat→ate, take→took, buy→bought.',
      [['We went to Nha Trang last summer.', 'Hè rồi chúng tôi đi Nha Trang.'], ['I saw the sunrise.', 'Tôi đã ngắm bình minh.'], ['She took a lot of photos.', 'Cô ấy chụp rất nhiều ảnh.']]],
    [
      { kind: 'mc', question: "Quá khứ của 'eat' là gì?", options: ['ate', 'eated', 'eaten', 'eats'], answer: 'ate' },
      { kind: 'mc', question: "Quá khứ của 'buy' là gì?", options: ['bought', 'buyed', 'brought', 'bough'], answer: 'bought' },
      { kind: 'fill', sentence: 'We ___ to Nha Trang last summer.', choices: ['went', 'go', 'gone'], answer: 'went' },
      { kind: 'fill', sentence: 'She ___ a lot of photos.', choices: ['took', 'take', 'taken'], answer: 'took' },
      { kind: 'order', words: ['We', 'ate', 'fresh', 'seafood'], answer: 'We ate fresh seafood' },
      { kind: 'listen', text: 'I saw the sunrise at the beach.', options: ['I saw the sunrise at the beach.', 'I saw the sunset at the beach.', 'I saw the sunrise at the bridge.'], answer: 'I saw the sunrise at the beach.' },
    ]),
  L(19, '💪', 'Can, Must & Should', 'Có thể, Phải & Nên',
    [
      ['must', 'phải', 'You must wear a helmet.'],
      ['should', 'nên', 'You should sleep early.'],
      ['can', 'có thể', 'I can speak two languages.'],
      ['rule', 'quy định / luật', 'Follow the class rules, please.'],
      ['helmet', 'mũ bảo hiểm', 'Always wear your helmet.'],
    ],
    ['Modal verbs', 'Động từ khuyết thiếu', 'can = ability, should = advice, must = obligation. After them, use the base verb: You must wear a helmet.', 'can = có thể (khả năng), should = nên (lời khuyên), must = phải (bắt buộc). Sau chúng dùng động từ nguyên mẫu: You must wear a helmet.',
      [['I can speak two languages.', 'Tôi có thể nói hai thứ tiếng.'], ['You should sleep early.', 'Bạn nên ngủ sớm.'], ['You must wear a helmet.', 'Bạn phải đội mũ bảo hiểm.']]],
    [
      { kind: 'mc', question: 'You ___ wear a helmet. (bắt buộc)', options: ['must', 'can', 'may', 'could'], answer: 'must' },
      { kind: 'mc', question: 'You ___ sleep early. (lời khuyên)', options: ['should', 'must', 'can', 'will'], answer: 'should' },
      { kind: 'fill', sentence: 'I ___ speak two languages.', choices: ['can', 'must', 'should'], answer: 'can' },
      { kind: 'fill', sentence: 'Follow the class ___, please.', choices: ['rules', 'rulers', 'roles'], answer: 'rules' },
      { kind: 'order', words: ['You', 'must', 'wear', 'a', 'helmet'], answer: 'You must wear a helmet' },
      { kind: 'listen', text: 'You should sleep early.', options: ['You should sleep early.', 'You should sleep late.', 'You could sleep early.'], answer: 'You should sleep early.' },
    ]),
  L(20, '🌟', 'Dreams & Plans', 'Ước mơ & Kế hoạch',
    [
      ['dream', 'ước mơ', 'My dream is to travel the world.'],
      ['future', 'tương lai', 'In the future, I want to be a pilot.'],
      ['hope', 'hy vọng', 'I hope to pass the exam.'],
      ['become', 'trở thành', 'She wants to become a doctor.'],
      ['practice', 'luyện tập', 'Practice English every day to improve.'],
    ],
    ['want to / going to', 'want to / going to', 'Dreams: I want to become… Plans: I am going to study abroad next year.', 'Ước mơ: I want to become… (tôi muốn trở thành…). Kế hoạch: I am going to study abroad (tôi sẽ đi du học).',
      [['I want to become a pilot.', 'Tôi muốn trở thành phi công.'], ['She is going to study abroad.', 'Cô ấy sẽ đi du học.'], ['I hope to pass the exam.', 'Tôi hy vọng thi đậu.']]],
    [
      { kind: 'mc', question: 'She wants to ___ a doctor.', options: ['become', 'becomes', 'became', 'becoming'], answer: 'become' },
      { kind: 'mc', question: "'Tương lai' trong tiếng Anh là gì?", options: ['future', 'feature', 'picture', 'nature'], answer: 'future' },
      { kind: 'fill', sentence: 'I ___ to pass the exam.', choices: ['hope', 'dream', 'practice'], answer: 'hope' },
      { kind: 'fill', sentence: 'I am ___ to study abroad next year.', choices: ['going', 'want', 'hoping'], answer: 'going' },
      { kind: 'order', words: ['My', 'dream', 'is', 'to', 'travel', 'the', 'world'], answer: 'My dream is to travel the world' },
      { kind: 'listen', text: 'Practice English every day to improve.', options: ['Practice English every day to improve.', 'Practice English every week to improve.', 'Practice English every day to prove.'], answer: 'Practice English every day to improve.' },
    ]),
];

export const FOUNDATIONS: Course = {
  id: 'foundations',
  emoji: '🗺️',
  color: 'bg-emerald-400',
  titleEn: 'English Foundations (Level 1–20)',
  titleVi: 'Nền tảng tiếng Anh (Cấp 1–20)',
  descEn: 'From zero to confident basics, one level at a time',
  descVi: 'Từ con số 0 đến nền tảng vững chắc, từng cấp một',
  levelKeywords: [],
  units: [
    { id: 'found_u1', titleEn: 'Levels 1–5 · First Steps', titleVi: 'Cấp 1–5 · Bước đầu tiên', lessons: LESSONS.slice(0, 5) },
    { id: 'found_u2', titleEn: 'Levels 6–10 · My World', titleVi: 'Cấp 6–10 · Thế giới của tôi', lessons: LESSONS.slice(5, 10) },
    { id: 'found_u3', titleEn: 'Levels 11–15 · Out & About', titleVi: 'Cấp 11–15 · Ra ngoài thế giới', lessons: LESSONS.slice(10, 15) },
    { id: 'found_u4', titleEn: 'Levels 16–20 · Level Up', titleVi: 'Cấp 16–20 · Nâng trình', lessons: LESSONS.slice(15, 20) },
  ],
};
